// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Paganod.Data.Context;

namespace Paganod.Data.Migrations
{
    [DbContext(typeof(PaganodContext))]
    partial class PaganodContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("paganod")
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("Paganod.Data.Context.WeatherForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Summary")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("int");

                    b.Property<string>("WeatherForecastId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(36)")
                        .HasDefaultValueSql("(UUID())");

                    b.HasKey("Id");

                    b.ToTable("WeatherForecasts", "paganod");
                });

            modelBuilder.Entity("Paganod.Data.Entities.ApiConnector", b =>
                {
                    b.Property<string>("ApiConnectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(36)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<string>("BaseUrl")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("ConnectorId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OpenAPISpec")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Version")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ApiConnectorId");

                    b.ToTable("ApiConnectors", "paganod");
                });

            modelBuilder.Entity("Paganod.Data.Entities.Connector", b =>
                {
                    b.Property<string>("ConnectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(36)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ConnectorId");

                    b.ToTable("Connectors", "paganod");
                });

            modelBuilder.Entity("Paganod.Data.Entities.FileLink", b =>
                {
                    b.Property<string>("FileLinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(36)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Extension")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("FileName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Link")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("char(36)");

                    b.Property<string>("RecordType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("FileLinkId");

                    b.ToTable("FileLinks", "paganod");
                });

            modelBuilder.Entity("Paganod.Data.Entities.Plugin", b =>
                {
                    b.Property<string>("PluginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(36)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PluginName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<byte[]>("PluginReference")
                        .HasColumnType("longblob");

                    b.HasKey("PluginId");

                    b.ToTable("Plugins", "paganod");
                });

            modelBuilder.Entity("Paganod.Data.Entities.Process", b =>
                {
                    b.Property<string>("ProcessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(36)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<string>("Action")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Arguments_Json")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("ConnectorId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExpectedOutput_Json")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OpType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("WorkflowId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.HasKey("ProcessId");

                    b.HasIndex("WorkflowId");

                    b.ToTable("Processes", "paganod");
                });

            modelBuilder.Entity("Paganod.Data.Entities.RecordForm", b =>
                {
                    b.Property<string>("RecordFormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(36)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FormJson")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("RecordFormId");

                    b.ToTable("RecordForms", "paganod");
                });

            modelBuilder.Entity("Paganod.Data.Entities.RecordView", b =>
                {
                    b.Property<string>("RecordViewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(36)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("QueryAsString")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("SchemaModelId")
                        .HasColumnType("char(36)");

                    b.HasKey("RecordViewId");

                    b.ToTable("RecordViews", "paganod");
                });

            modelBuilder.Entity("Paganod.Data.Entities.RecordViewColumn", b =>
                {
                    b.Property<string>("RecordViewColumnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(36)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.HasKey("RecordViewColumnId");

                    b.ToTable("RecordViewColumns", "paganod");
                });

            modelBuilder.Entity("Paganod.Data.Entities.SchemaColumn", b =>
                {
                    b.Property<Guid>("SchemaColumnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("OptionsJson")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("SchemaModelId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("SchemaColumnId");

                    b.HasIndex("SchemaModelId");

                    b.ToTable("SchemaColumn");
                });

            modelBuilder.Entity("Paganod.Data.Entities.SchemaModel", b =>
                {
                    b.Property<string>("SchemaModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(36)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PrimaryKeyColumnName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("RecordDisplayName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("RecordName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("TableDisplayName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("TableName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("SchemaModelId");

                    b.ToTable("SchemaModels", "paganod");
                });

            modelBuilder.Entity("Paganod.Data.Entities.Script", b =>
                {
                    b.Property<string>("ScriptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(36)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Language")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("LocationType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ScriptId");

                    b.ToTable("Scripts", "paganod");
                });

            modelBuilder.Entity("Paganod.Data.Entities.Solution", b =>
                {
                    b.Property<string>("SolutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(36)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("InstalledBy")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("InstalledOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IsConfigurable")
                        .IsRequired()
                        .HasColumnType("varchar(5) CHARACTER SET utf8mb4");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Version")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("SolutionId");

                    b.ToTable("Solutions", "paganod");
                });

            modelBuilder.Entity("Paganod.Data.Entities.SolutionItem", b =>
                {
                    b.Property<string>("SolutionItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(36)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<int>("ComponentId")
                        .HasColumnType("int");

                    b.Property<string>("ComponentType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SolutionId")
                        .HasColumnType("int");

                    b.HasKey("SolutionItemId");

                    b.ToTable("SolutionItems", "paganod");
                });

            modelBuilder.Entity("Paganod.Data.Entities.Trigger", b =>
                {
                    b.Property<string>("TriggerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(36)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SubType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("TriggerId");

                    b.ToTable("Triggers", "paganod");
                });

            modelBuilder.Entity("Paganod.Data.Entities.WebFlow", b =>
                {
                    b.Property<string>("WebFlowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(36)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("FinishedProcessId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ScriptId")
                        .HasColumnType("char(36)");

                    b.HasKey("WebFlowId");

                    b.ToTable("WebFlows", "paganod");
                });

            modelBuilder.Entity("Paganod.Data.Entities.WebFlowParameters", b =>
                {
                    b.Property<string>("WebFlowParametersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(36)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Value")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("WebFlowParametersId");

                    b.ToTable("WebFlowParameters", "paganod");
                });

            modelBuilder.Entity("Paganod.Data.Entities.WebResource", b =>
                {
                    b.Property<string>("WebResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(36)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<string>("Content")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PreviewImage")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ShortName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("WebResourceId");

                    b.ToTable("WebResources", "paganod");
                });

            modelBuilder.Entity("Paganod.Data.Entities.Workflow", b =>
                {
                    b.Property<string>("WorkflowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(36)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("WorkflowId");

                    b.ToTable("Workflows", "paganod");
                });

            modelBuilder.Entity("Paganod.Data.Entities.Process", b =>
                {
                    b.HasOne("Paganod.Data.Entities.Workflow", null)
                        .WithMany("Processes")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Paganod.Data.Entities.SchemaColumn", b =>
                {
                    b.HasOne("Paganod.Data.Entities.SchemaModel", null)
                        .WithMany("Columns")
                        .HasForeignKey("SchemaModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Paganod.Data.Entities.SchemaModel", b =>
                {
                    b.Navigation("Columns");
                });

            modelBuilder.Entity("Paganod.Data.Entities.Workflow", b =>
                {
                    b.Navigation("Processes");
                });
#pragma warning restore 612, 618
        }
    }
}
